#!/usr/bin/env python3
"""Builds a real, installable 3DS forwarder CIA for a DS ROM.

The forwarder is a genuine CIA — a real NCCH with the DS ROM's own
icon/title, built with devkitARM + bannertool + makerom — so it shows
up as a normal icon on the emulated 3DS HOME Menu (like a real modded
3DS's forwarders do). Its actual 3DS code never does anything
meaningful: GMainWindow::BootGame() (see ds_forwarder_registry.h)
intercepts it by title ID before it would ever really run, and boots
the target DS ROM in melonDS instead.

Usage:
    make_ds_forwarder.py path/to/game.nds [--output-dir DIR]

Requires (paths overridable via --bannertool/--makerom/--devkitarm):
  - bannertool  (SMDH/banner builder)
  - makerom     (NCCH/CIA builder)
  - devkitARM's arm-none-eabi-gcc + libctru (compiles the stub app)

After building, install the .cia through Azahar's own
File > Install CIA — this script only builds and registers it.
"""

import argparse
import hashlib
import os
import shutil
import struct
import subprocess
import sys
import tempfile
import textwrap

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required: pip3 install pillow")

# --- NDS icon decoding (mirrors src/citra_qt/util/nds_icon.cpp) ------------

BANNER_OFFSET_FIELD = 0x68
BITMAP_OFFSET = 0x20
PALETTE_OFFSET = 0x220


def scale5to8(v5):
    return (v5 << 3) | (v5 >> 2)


def decode_nds_icon(rom_path):
    """Returns a 32x32 PIL Image (RGBA), or None if the ROM has no banner."""
    with open(rom_path, "rb") as f:
        f.seek(BANNER_OFFSET_FIELD)
        (banner_offset,) = struct.unpack("<I", f.read(4))
        if banner_offset == 0:
            return None

        f.seek(banner_offset + BITMAP_OFFSET)
        bitmap = f.read(512)
        f.seek(banner_offset + PALETTE_OFFSET)
        palette_raw = f.read(32)

    palette = []
    for i in range(16):
        raw = palette_raw[i * 2] | (palette_raw[i * 2 + 1] << 8)
        r, g, b = scale5to8(raw & 0x1F), scale5to8((raw >> 5) & 0x1F), scale5to8((raw >> 10) & 0x1F)
        palette.append((0, 0, 0, 0) if i == 0 else (r, g, b, 255))

    img = Image.new("RGBA", (32, 32))
    for tile in range(16):
        tile_col, tile_row = tile % 4, tile // 4
        base = tile * 32
        for row in range(8):
            for b in range(4):
                byte = bitmap[base + row * 4 + b]
                left, right = byte & 0x0F, (byte >> 4) & 0x0F
                x, y = tile_col * 8 + b * 2, tile_row * 8 + row
                img.putpixel((x, y), palette[left])
                img.putpixel((x + 1, y), palette[right])
    return img


# --- Stub 3DS app source -----------------------------------------------

STUB_MAIN_C = textwrap.dedent(
    """\
    // Auto-generated by make_ds_forwarder.py — this app is never meant
    // to actually run under Azahar (see ds_forwarder_registry.h), but
    // stays harmless and exits cleanly if it ever does (e.g. on real
    // hardware, or if the forwarder registry entry gets lost).
    #include <3ds.h>
    #include <stdio.h>

    int main(void) {
        gfxInitDefault();
        consoleInit(GFX_TOP, NULL);
        printf("This is an Azahar DS forwarder.\\n\\n"
               "It has no game of its own to run --\\n"
               "Azahar should have redirected to the\\n"
               "linked DS ROM before this ever showed.\\n\\n"
               "Press START to exit.");

        while (aptMainLoop()) {
            hidScanInput();
            if (hidKeysDown() & KEY_START) break;
            gfxFlushBuffers();
            gfxSwapBuffers();
            gspWaitForVBlank();
        }

        gfxExit();
        return 0;
    }
    """
)


def build_stub_elf(work_dir, devkitarm, log):
    gcc = os.path.join(devkitarm, "bin", "arm-none-eabi-gcc")
    ctrulib = "/opt/devkitpro/libctru"
    if not os.path.isfile(gcc):
        sys.exit(f"arm-none-eabi-gcc not found at {gcc}")

    main_c = os.path.join(work_dir, "main.c")
    with open(main_c, "w") as f:
        f.write(STUB_MAIN_C)

    common_flags = [
        "-march=armv6k", "-mtune=mpcore", "-mfloat-abi=hard", "-mtp=soft",
        "-Wall", "-O2", "-mword-relocations", "-fomit-frame-pointer",
        "-ffunction-sections", "-D__3DS__",
        f"-I{ctrulib}/include",
    ]

    obj = os.path.join(work_dir, "main.o")
    log(f"Compiling stub app -> {obj}")
    subprocess.run([gcc, *common_flags, "-c", main_c, "-o", obj], check=True)

    elf = os.path.join(work_dir, "forwarder.elf")
    log(f"Linking stub app -> {elf}")
    subprocess.run(
        [
            gcc, "-specs=3dsx.specs", *common_flags,
            obj, f"-L{ctrulib}/lib", "-lctru", "-lm", "-o", elf,
        ],
        check=True,
    )
    return elf


# --- Icon/banner via bannertool -----------------------------------------

def _build_silent_wav(duration_seconds=1.0, sample_rate=32728):
    # A zero-length data chunk is technically a valid WAV file, but
    # bannertool's banner audio is meant to loop for as long as an icon
    # stays highlighted on the HOME Menu — some encoders either reject
    # a zero-sample source outright or fall back to their own default
    # tone when there's nothing to actually loop. A real (if short)
    # run of true-zero 16-bit PCM samples is unambiguous silence
    # either way. 32728 Hz matches the sample rate real 3DS banner
    # audio conventionally uses.
    num_samples = int(duration_seconds * sample_rate)
    pcm = b"\x00\x00" * num_samples
    data_size = len(pcm)
    fmt_chunk = struct.pack("<HHIIHH", 1, 1, sample_rate, sample_rate * 2, 2, 16)
    riff_size = 4 + (8 + len(fmt_chunk)) + (8 + data_size)
    return (
        b"RIFF" + struct.pack("<I", riff_size) + b"WAVE" +
        b"fmt " + struct.pack("<I", len(fmt_chunk)) + fmt_chunk +
        b"data" + struct.pack("<I", data_size) + pcm
    )


SILENT_WAV = _build_silent_wav()


def build_smdh_and_banner(work_dir, bannertool, title, icon, icon_png, log):
    smdh = os.path.join(work_dir, "forwarder.smdh")
    log(f"Building SMDH ({title!r}) -> {smdh}")
    subprocess.run(
        [
            bannertool, "makesmdh",
            "-s", title, "-l", title, "-p", "Azahar",
            "-i", icon_png, "-o", smdh,
            # Real commercial titles set "extendedbanner" whenever they
            # ship a full CWAV-audio banner (which is exactly what
            # build_smdh_and_banner does below) — leaving it unset while
            # a real audio-bearing banner is present looks like a plain
            # source of the HOME Menu's "your banner doesn't match what
            # I expected" error tone as soon as the icon is highlighted,
            # even though the audio data itself is genuine silence.
            "-f", "visible,extendedbanner",
        ],
        check=True,
    )

    # The banner image is a fixed 256x128 (bannertool enforces this
    # exactly) — a separate canvas from the 48x48 SMDH icon, not just
    # the icon at a different size. Center the icon, upscaled a bit
    # further, on a plain background.
    banner_img = Image.new("RGBA", (256, 128), (32, 32, 48, 255))
    banner_icon = icon.resize((96, 96), Image.NEAREST)
    banner_img.paste(banner_icon, ((256 - 96) // 2, (128 - 96) // 2), banner_icon)
    banner_png = os.path.join(work_dir, "banner.png")
    banner_img.save(banner_png)

    silence_wav = os.path.join(work_dir, "silence.wav")
    with open(silence_wav, "wb") as f:
        f.write(SILENT_WAV)

    banner = os.path.join(work_dir, "forwarder.bnr")
    log(f"Building banner -> {banner}")
    subprocess.run(
        [
            bannertool, "makebanner",
            "-i", banner_png, "-a", silence_wav, "-o", banner,
        ],
        check=True,
    )
    return smdh, banner


# --- CIA packaging via makerom -------------------------------------------

def build_cia(work_dir, makerom, rsf_template, elf, smdh, banner, title,
              unique_id, product_code, output_cia, log):
    empty_romfs = os.path.join(work_dir, "empty_romfs")
    os.makedirs(empty_romfs, exist_ok=True)

    log(f"Packaging CIA -> {output_cia}")
    subprocess.run(
        [
            makerom, "-f", "cia", "-o", output_cia,
            "-rsf", rsf_template,
            "-elf", elf, "-icon", smdh, "-banner", banner,
            "-target", "t", "-exefslogo",
            f"-DAPP_TITLE={title}",
            f"-DAPP_PRODUCT_CODE={product_code}",
            f"-DAPP_ROMFS={empty_romfs}",
            "-DAPP_CATEGORY=Application",
            f"-DAPP_UNIQUE_ID={unique_id}",
            "-DAPP_USE_ON_SD=true",
            "-DAPP_ENCRYPTED=false",
            "-DAPP_MEMORY_TYPE=Application",
            "-DAPP_SYSTEM_MODE=64MB",
            "-DAPP_SYSTEM_MODE_EXT=Legacy",
            "-DAPP_CPU_SPEED=268MHz",
            "-DAPP_ENABLE_L2_CACHE=false",
            "-DAPP_VERSION_MAJOR=1",
        ],
        check=True,
    )


# --- Registry -------------------------------------------------------------

def register_forwarder(user_dir, program_id_hex, rom_path, log):
    registry_path = os.path.join(user_dir, "ds_forwarders.txt")
    line = f"{program_id_hex}={os.path.abspath(rom_path)}\n"

    existing = ""
    if os.path.isfile(registry_path):
        with open(registry_path) as f:
            existing = f.read()
    # Replace any stale entry for the same title ID (re-running this
    # script for the same ROM should update in place, not duplicate).
    lines = [l for l in existing.splitlines() if not l.startswith(program_id_hex + "=")]
    lines.append(line.strip())

    with open(registry_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    log(f"Registered {program_id_hex} -> {rom_path} in {registry_path}")


# --- Main -----------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                      formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("rom", help="Path to the .nds ROM to forward to")
    parser.add_argument("--title", help="Override the forwarder's title "
                        "(defaults to the ROM's filename)")
    parser.add_argument("--output-dir", default=".", help="Where to write the .cia")
    parser.add_argument("--user-dir", required=True,
                        help="Azahar's UserDir (where ds_forwarders.txt lives)")
    parser.add_argument("--bannertool", default=os.path.expanduser(
        "~/Desktop/bannertool/output/mac-x86_64/bannertool"))
    parser.add_argument("--makerom", default=os.path.expanduser(
        "~/Desktop/Project_CTR/makerom/bin/makerom"))
    parser.add_argument("--rsf-template", default=os.path.expanduser(
        "~/Desktop/bannertool/buildtools/3ds/template.rsf"))
    parser.add_argument("--devkitarm", default="/opt/devkitpro/devkitARM")
    args = parser.parse_args()

    def log(msg):
        print(f"[make_ds_forwarder] {msg}", file=sys.stderr)

    rom_path = os.path.abspath(args.rom)
    if not os.path.isfile(rom_path):
        sys.exit(f"ROM not found: {rom_path}")

    for tool_path, name in [(args.bannertool, "bannertool"), (args.makerom, "makerom"),
                             (args.rsf_template, "RSF template")]:
        if not os.path.isfile(tool_path):
            sys.exit(f"{name} not found at {tool_path}")

    icon = decode_nds_icon(rom_path)
    if icon is None:
        sys.exit(f"{rom_path} has no icon/banner block — can't build a forwarder for it.")

    # Use the ROM's own filename rather than its internal banner title:
    # Nintendo's own banners are frequently ambiguous on purpose (e.g.
    # both Pokemon Black and Black 2 report just "Pokémon" as their
    # first title line), which collapses distinct games to the same
    # HOME Menu label. The filename the user already organizes their
    # ROMs by is guaranteed distinct and always identifies the game.
    title = args.title or os.path.splitext(os.path.basename(rom_path))[0]
    log(f"Title: {title!r}")

    # 32-bit low title ID + a matching short product code, both
    # deterministically derived from the ROM's own path so re-running
    # this script for the same file reuses the same identity instead
    # of registering a duplicate forwarder each time.
    digest = hashlib.sha256(rom_path.encode()).digest()
    # RSF's UniqueId is nominally a 24-bit field, but test-key CIA
    # builds reject anything past roughly 16 bits in practice
    # (confirmed empirically — 0xFFFFFF-range values fail with "Unique
    # ID is out of range", 0x1000 doesn't). 16 bits is still far more
    # than enough entropy to avoid collisions across a personal ROM
    # collection. makerom builds the real title ID's low 32 bits as
    # (UniqueId << 8) | variation (variation 0x00 for a plain
    # application) — the registry has to record that same combined
    # value, since that's what ReadProgramId() actually reports back
    # for the installed CIA.
    unique_id = struct.unpack(">H", digest[:2])[0] & 0xFFFF
    if unique_id == 0:
        unique_id = 1
    product_code = "DSF" + digest[:1].hex().upper()
    program_id_hex = f"00040000{(unique_id << 8):08x}"

    with tempfile.TemporaryDirectory(prefix="ds_forwarder_") as work_dir:
        icon_png = os.path.join(work_dir, "icon.png")
        # Nearest-neighbor upscale from the native 32x32 keeps the
        # pixelated look instead of blurring it — matches how real
        # forwarder generators usually present a small source icon.
        icon.resize((48, 48), Image.NEAREST).save(icon_png)

        elf = build_stub_elf(work_dir, args.devkitarm, log)
        smdh, banner = build_smdh_and_banner(work_dir, args.bannertool, title, icon, icon_png, log)

        os.makedirs(args.output_dir, exist_ok=True)
        safe_name = "".join(c if c.isalnum() or c in " -_" else "_" for c in title).strip()
        output_cia = os.path.join(args.output_dir, f"{safe_name}.cia")

        build_cia(work_dir, args.makerom, args.rsf_template, elf, smdh, banner,
                 title, unique_id, product_code, output_cia, log)

    register_forwarder(args.user_dir, program_id_hex, rom_path, log)

    print(output_cia)
    log("Done. Install this .cia through Azahar's File > Install CIA, "
        "then it'll show up on the HOME Menu with this ROM's own icon.")


if __name__ == "__main__":
    main()
